
version: '3.1'

services:


  gateway:
    image: traefik:v2.11.21
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./gateway:/etc/traefik"
      - "./certs:/certs"

  backend:
    image: cg-schools-api
    container_name: schools-service
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8001:8001'

